services:
    Overblog\ActiveMqBundle\Command\ConsumerCommand:
        tags:
            - { name: console.command, command: activemq:consumer }

    Overblog\ActiveMqBundle\Command\ProducerCommand:
        tags:
            - { name: console.command, command: activemq:producer }
